#+title:     Ectorepo: AMD ROCm
#+author:    David Conner
#+email:     noreply@te.xel.io
#+PROPERTY: header-args+ :comments none :var enable-restclient=(setq-local restclient-enable-eval "yes")

A list of AMD ROCm repositories. To learn how to use this Repo repo, see the
the [[https://github.com/ectorepo/ectorepo][ectorepo/ectorepo]] Repo ... repo.

#+begin_src xml :tangle default.xml
<manifest>
  <include name="_remotes.xml"/>
  <default remote="github" sync-j="8" revision="refs/heads/master"/>
  <include name="rocm.xml"/>
</manifest>
#+end_src

Check rates:

#+begin_src emacs-lisp :results value code :exports code
(ghub-graphql-rate-limit)
#+end_src

To avoid confirmations

#+begin_src emacs-lisp
(setq-local org-confirm-babel-evaluate nil)
#+end_src

* Babel Setup

Get the core repositories. These should go into =/data/ecto/ROCmSoftwarePlatform/rocm=.

#+name: nrepos
#+begin_src emacs-lisp
100
#+end_src

#+RESULTS: nrepos
: 100

For some reason =:var nrepos=200= doesn't properly substitute here, so =:noweb
yes= is required. However, 100 is the max on sorted results anyways.

* ROCm

The list of repos will cycle (100 results). Retain these random libs for a minute:

| ROCm/amd_matrix_instruction_calculator | query device to calculate flops rate, capabilities |
| ROCm/gsplat                            | guassian splatting                                |


Clone bundle sizes

#+name: rocmBundles
#+begin_src emacs-lisp :var nrepos=100 :results value table :exports code :noweb yes
(setq -gql-data
      (ghub-graphql
       (graphql-query ((organization
                        :arguments ((login . "ROCm"))
                        (repositories
                         :arguments ((first . 100)
                                     (orderBy . ((field . UPDATED_AT)
                                                 (direction . DESC))))
                         (edges
                          (node (owner login)
                                name
                                (defaultBranchRef prefix name)
                                url
                                updatedAt
                                diskUsage
                                isFork
                                isArchived))))))))

(thread-first
  (thread-last
    (a-get* (nthcdr 0 -gql-data) 'data 'organization 'repositories 'edges)
    (mapcar (lambda (el) (a-get* el 'node)))

    ;; filter archived repos
    (seq-filter (lambda (el) (not (a-get* el 'isFork))))
    (seq-filter (lambda (el) (not (a-get* el 'isArchived))))
    (mapcar (lambda (el)
              (flatten-list
               (list
                (a-get* el 'diskUsage)
                (a-get* el 'owner 'login)
                (a-get* el 'defaultBranchRef 'prefix)
                (a-get* el 'defaultBranchRef 'name)
                (mapcar (lambda (repo-keys)
                          (a-get* el repo-keys))
                        '(name
                          updatedAt
                          isFork
                          isArchived
                          url))))))))
#+end_src

#+RESULTS: rocmBundles
| 5966336 | ROCm | refs/heads/ | develop                | rocm-libraries             | 2026-05-06T16:55:01Z | https://github.com/ROCm/rocm-libraries             |
|   95303 | ROCm | refs/heads/ | main                   | gpu-operator               | 2026-05-06T16:51:58Z | https://github.com/ROCm/gpu-operator               |
|  161501 | ROCm | refs/heads/ | develop                | MIVisionX                  | 2026-05-06T16:47:31Z | https://github.com/ROCm/MIVisionX                  |
| 2480174 | ROCm | refs/heads/ | develop                | rocm-systems               | 2026-05-06T16:37:06Z | https://github.com/ROCm/rocm-systems               |
|   23922 | ROCm | refs/heads/ | main                   | TheRock                    | 2026-05-06T16:22:54Z | https://github.com/ROCm/TheRock                    |
|  209247 | ROCm | refs/heads/ | main                   | aiter                      | 2026-05-06T16:22:45Z | https://github.com/ROCm/aiter                      |
|   16472 | ROCm | refs/heads/ | main                   | ATOM                       | 2026-05-06T16:11:40Z | https://github.com/ROCm/ATOM                       |
|  519535 | ROCm | refs/heads/ | amd-staging            | ROCgdb                     | 2026-05-06T15:52:52Z | https://github.com/ROCm/ROCgdb                     |
|    4127 | ROCm | refs/heads/ | main                   | cvs                        | 2026-05-06T15:41:27Z | https://github.com/ROCm/cvs                        |
|   37001 | ROCm | refs/heads/ | main                   | roc-optiq                  | 2026-05-06T15:26:09Z | https://github.com/ROCm/roc-optiq                  |
|   20444 | ROCm | refs/heads/ | amd-develop            | HIPIFY                     | 2026-05-06T15:23:16Z | https://github.com/ROCm/HIPIFY                     |
|   42493 | ROCm | refs/heads/ | develop                | clr                        | 2026-05-06T15:15:22Z | https://github.com/ROCm/clr                        |
|   23340 | ROCm | refs/heads/ | amd-staging            | SPIRV-LLVM-Translator      | 2026-05-06T15:04:19Z | https://github.com/ROCm/SPIRV-LLVM-Translator      |
|   23839 | ROCm | refs/heads/ | develop                | rocCV                      | 2026-05-06T14:07:07Z | https://github.com/ROCm/rocCV                      |
|   97290 | ROCm | refs/heads/ | develop                | composable_kernel          | 2026-05-06T13:29:28Z | https://github.com/ROCm/composable_kernel          |
|    1169 | ROCm | refs/heads/ | develop                | TransferBench              | 2026-05-06T12:30:40Z | https://github.com/ROCm/TransferBench              |
|     308 | ROCm | refs/heads/ | main                   | pyrsmi                     | 2026-05-06T11:35:55Z | https://github.com/ROCm/pyrsmi                     |
|   28158 | ROCm | refs/heads/ | develop                | librocdxg                  | 2026-05-06T10:43:24Z | https://github.com/ROCm/librocdxg                  |
|  147060 | ROCm | refs/heads/ | develop                | ROCm                       | 2026-05-06T10:05:40Z | https://github.com/ROCm/ROCm                       |
|   16754 | ROCm | refs/heads/ | main                   | mori                       | 2026-05-06T09:56:58Z | https://github.com/ROCm/mori                       |
|   11789 | ROCm | refs/heads/ | develop                | hip-tests                  | 2026-05-06T09:22:57Z | https://github.com/ROCm/hip-tests                  |
|    8170 | ROCm | refs/heads/ | main                   | FlyDSL                     | 2026-05-06T08:59:44Z | https://github.com/ROCm/FlyDSL                     |
|   28538 | ROCm | refs/heads/ | develop                | hip                        | 2026-05-06T05:54:07Z | https://github.com/ROCm/hip                        |
|    1162 | ROCm | refs/heads/ | main                   | spur                       | 2026-05-06T05:20:18Z | https://github.com/ROCm/spur                       |
|    9819 | ROCm | refs/heads/ | master                 | ROCmValidationSuite        | 2026-05-06T05:16:16Z | https://github.com/ROCm/ROCmValidationSuite        |
|   30852 | ROCm | refs/heads/ | dev                    | TransformerEngine          | 2026-05-06T04:08:30Z | https://github.com/ROCm/TransformerEngine          |
|  176451 | ROCm | refs/heads/ | develop                | AMDMIGraphX                | 2026-05-06T03:47:29Z | https://github.com/ROCm/AMDMIGraphX                |
|    1168 | ROCm | refs/heads/ | main                   | rocm-installer-runfile     | 2026-05-06T01:41:43Z | https://github.com/ROCm/rocm-installer-runfile     |
|     556 | ROCm | refs/heads/ | main                   | kernel-module-management   | 2026-05-05T23:45:13Z | https://github.com/ROCm/kernel-module-management   |
|   20022 | ROCm | refs/heads/ | main                   | device-config-manager      | 2026-05-05T22:33:54Z | https://github.com/ROCm/device-config-manager      |
|  161039 | ROCm | refs/heads/ | master                 | rocm-jax                   | 2026-05-05T22:20:04Z | https://github.com/ROCm/rocm-jax                   |
| 1379577 | ROCm | refs/heads/ | main                   | device-metrics-exporter    | 2026-05-05T19:55:53Z | https://github.com/ROCm/device-metrics-exporter    |
|   20083 | ROCm | refs/heads/ | amd-mainline           | amdsmi                     | 2026-05-05T19:38:58Z | https://github.com/ROCm/amdsmi                     |
| 2094050 | ROCm | refs/heads/ | develop                | rocMLIR                    | 2026-05-05T19:23:41Z | https://github.com/ROCm/rocMLIR                    |
| 2063758 | ROCm | refs/heads/ | release                | rocm-blogs                 | 2026-05-05T16:45:47Z | https://github.com/ROCm/rocm-blogs                 |
|   13982 | ROCm | refs/heads/ | main                   | hrx                        | 2026-05-05T15:34:07Z | https://github.com/ROCm/hrx                        |
|     138 | ROCm | refs/heads/ | main                   | repo-digest                | 2026-05-05T09:22:49Z | https://github.com/ROCm/repo-digest                |
|   15824 | ROCm | refs/heads/ | aomp-dev               | aomp                       | 2026-05-05T09:20:03Z | https://github.com/ROCm/aomp                       |
|    3529 | ROCm | refs/heads/ | develop                | amdgpu-docs                | 2026-05-04T20:47:21Z | https://github.com/ROCm/amdgpu-docs                |
|   27443 | ROCm | refs/heads/ | main                   | gpuaidev                   | 2026-05-04T18:49:38Z | https://github.com/ROCm/gpuaidev                   |
|   43760 | ROCm | refs/heads/ | develop                | rocAL                      | 2026-05-04T18:30:57Z | https://github.com/ROCm/rocAL                      |
|   15665 | ROCm | refs/heads/ | develop                | rocm-install-on-linux      | 2026-05-04T18:30:24Z | https://github.com/ROCm/rocm-install-on-linux      |
|    4039 | ROCm | refs/heads/ | develop_deprecated     | hipDNN                     | 2026-05-04T17:23:40Z | https://github.com/ROCm/hipDNN                     |
|    1226 | ROCm | refs/heads/ | amd-mainline           | rocm_bandwidth_test        | 2026-05-04T17:11:37Z | https://github.com/ROCm/rocm_bandwidth_test        |
|   86219 | ROCm | refs/heads/ | amd-staging_deprecated | ROCR-Runtime               | 2026-05-04T15:18:31Z | https://github.com/ROCm/ROCR-Runtime               |
| 3714032 | ROCm | refs/heads/ | master                 | amdgpu                     | 2026-05-04T15:18:00Z | https://github.com/ROCm/amdgpu                     |
|   18157 | ROCm | refs/heads/ | develop_deprecated     | rccl                       | 2026-05-04T15:16:23Z | https://github.com/ROCm/rccl                       |
| 1749522 | ROCm | refs/heads/ | develop_deprecated     | MIOpen                     | 2026-05-04T15:16:06Z | https://github.com/ROCm/MIOpen                     |
|   11596 | ROCm | refs/heads/ | main                   | gfx950-gluon-tutorials     | 2026-05-04T13:52:56Z | https://github.com/ROCm/gfx950-gluon-tutorials     |
|  151230 | ROCm | refs/heads/ | develop                | amd-rocm-programming-guide | 2026-05-04T11:36:53Z | https://github.com/ROCm/amd-rocm-programming-guide |
|   37783 | ROCm | refs/heads/ | release/1.5.3b2        | gsplat                     | 2026-05-04T10:54:15Z | https://github.com/ROCm/gsplat                     |
|    2492 | ROCm | refs/heads/ | main                   | rocm-xio                   | 2026-05-03T16:56:05Z | https://github.com/ROCm/rocm-xio                   |
|    9934 | ROCm | refs/heads/ | main                   | k8s-gpu-dra-driver         | 2026-05-03T16:25:48Z | https://github.com/ROCm/k8s-gpu-dra-driver         |
|    4237 | ROCm | refs/heads/ | develop                | rocm-docs-core             | 2026-05-03T14:51:26Z | https://github.com/ROCm/rocm-docs-core             |
|   64307 | ROCm | refs/heads/ | main                   | iris                       | 2026-05-02T20:59:23Z | https://github.com/ROCm/iris                       |
|     260 | ROCm | refs/heads/ | master                 | ROCm-docker                | 2026-05-02T20:58:54Z | https://github.com/ROCm/ROCm-docker                |
|  210153 | ROCm | refs/heads/ | develop                | rpp                        | 2026-05-02T20:58:01Z | https://github.com/ROCm/rpp                        |
|    7842 | ROCm | refs/heads/ | main                   | gpufort                    | 2026-05-02T20:57:22Z | https://github.com/ROCm/gpufort                    |
|   16038 | ROCm | refs/heads/ | master                 | k8s-device-plugin          | 2026-05-02T20:56:48Z | https://github.com/ROCm/k8s-device-plugin          |
|    4661 | ROCm | refs/heads/ | develop                | rocm-install-on-windows    | 2026-05-02T18:41:26Z | https://github.com/ROCm/rocm-install-on-windows    |
|     296 | ROCm | refs/heads/ | rocm                   | half                       | 2026-05-02T16:35:27Z | https://github.com/ROCm/half                       |
|     597 | ROCm | refs/heads/ | main                   | container-toolkit          | 2026-05-02T13:30:54Z | https://github.com/ROCm/container-toolkit          |
|    9764 | ROCm | refs/heads/ | develop_deprecated     | rocFFT                     | 2026-05-02T06:01:20Z | https://github.com/ROCm/rocFFT                     |
|   71276 | ROCm | refs/heads/ | main                   | aorta                      | 2026-05-01T14:24:39Z | https://github.com/ROCm/aorta                      |
|    6375 | ROCm | refs/heads/ | main                   | k8s-network-node-labeller  | 2026-04-30T22:12:26Z | https://github.com/ROCm/k8s-network-node-labeller  |
|     338 | ROCm | refs/heads/ | main                   | rocHPL                     | 2026-04-30T14:35:54Z | https://github.com/ROCm/rocHPL                     |
|   12122 | ROCm | refs/heads/ | develop_deprecated     | rocprofiler-systems        | 2026-04-30T09:40:19Z | https://github.com/ROCm/rocprofiler-systems        |
|    6427 | ROCm | refs/heads/ | amd-staging            | omnitrace                  | 2026-04-30T09:37:45Z | https://github.com/ROCm/omnitrace                  |
|    2798 | ROCm | refs/heads/ | amd-staging            | ROCdbgapi                  | 2026-04-29T22:19:18Z | https://github.com/ROCm/ROCdbgapi                  |
|    1273 | ROCm | refs/heads/ | main                   | rockbuilder                | 2026-04-29T21:48:15Z | https://github.com/ROCm/rockbuilder                |
|    1459 | ROCm | refs/heads/ | release/0.1.1          | hipThreads                 | 2026-04-29T19:06:56Z | https://github.com/ROCm/hipThreads                 |
|   23993 | ROCm | refs/heads/ | amd-staging            | rocm-examples              | 2026-04-29T18:49:18Z | https://github.com/ROCm/rocm-examples              |
|     689 | ROCm | refs/heads/ | main                   | jax-aiter                  | 2026-04-29T17:54:04Z | https://github.com/ROCm/jax-aiter                  |
|     112 | ROCm | refs/heads/ | main                   | amd-anp                    | 2026-04-29T16:38:02Z | https://github.com/ROCm/amd-anp                    |
|    3353 | ROCm | refs/heads/ | develop                | madengine                  | 2026-04-29T15:02:28Z | https://github.com/ROCm/madengine                  |
|    4944 | ROCm | refs/heads/ | main                   | omnistat                   | 2026-04-29T11:19:29Z | https://github.com/ROCm/omnistat                   |
|     559 | ROCm | refs/heads/ | develop                | rocHPCG                    | 2026-04-29T11:15:16Z | https://github.com/ROCm/rocHPCG                    |
|     795 | ROCm | refs/heads/ | master                 | HIP-CPU                    | 2026-04-29T09:17:56Z | https://github.com/ROCm/HIP-CPU                    |
|   15604 | ROCm | refs/heads/ | main                   | tritonBLAS                 | 2026-04-29T08:35:29Z | https://github.com/ROCm/tritonBLAS                 |
|    7894 | ROCm | refs/heads/ | main                   | tensorcast                 | 2026-04-29T07:43:53Z | https://github.com/ROCm/tensorcast                 |

Clone bundle sizes

#+name: fetchMetadata
#+headers: :var gh-org="FreeCAD" :jq-args "--raw-output" :eval query :results table
#+begin_src restclient :jq "sort_by(-.size) | map([.owner.login, .name, .size, .default_branch, .archived, .updated_at])[] | @csv"
:gh-graphql-url = https://api.github.com/graphql
:gh-url-base = https://api.github.com
:gh-url-path = orgs/:gh-org/repos
:gh-token := (auth-source-pass-get 'secret "api.github.com/dcunited001^ghub")

:headers = <<
Accept: application/vnd.github+json
Authorization: Bearer :gh-token
X-GitHub-Api-Version: 2022-11-28
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0
# User-Agent: dcunited001 # um okay that doesn't work
# https://docs.github.com/en/rest/using-the-rest-api/getting-started-with-the-rest-api?apiVersion=2022-11-28#user-agent

GET :gh-url-base/:gh-url-path
:headers
#+end_src

#+name: rocmMetadata
#+call: fetchMetadata(gh-org="rocm")

#+RESULTS: rocmMetadata
| ROCm | amdgpu                      | 3711580 | master                 | false | 2026-01-08T16:24:14Z |
| ROCm | llvm                        |  486348 | amd-common             | false | 2024-07-30T12:28:39Z |
| ROCm | hcc-clang-upgrade           |  372519 | clang_tot_upgrade      | false | 2025-11-25T20:22:01Z |
| ROCm | clang                       |  212441 | amd-common             | false | 2024-01-18T07:12:29Z |
| ROCm | rocBLAS                     |  186981 | develop_deprecated     | false | 2025-12-26T23:59:23Z |
| ROCm | ROCm                        |  145794 | develop                | false | 2026-01-08T23:18:42Z |
| ROCm | HIP-Examples                |  132888 | master                 | true  | 2025-12-01T14:00:07Z |
| ROCm | Tensile                     |  103092 | develop_deprecated     | false | 2025-12-31T04:36:24Z |
| ROCm | ROCR-Runtime                |   85381 | amd-staging_deprecated | false | 2025-11-11T01:58:34Z |
| ROCm | compiler-rt                 |   39118 | master                 | false | 2024-01-18T07:18:36Z |
| ROCm | lld                         |   37067 | amd-common             | false | 2024-01-18T12:58:14Z |
| ROCm | hip                         |   27260 | develop                | false | 2026-01-08T09:00:06Z |
| ROCm | hcc                         |   23626 | clang_tot_upgrade      | false | 2025-12-28T03:41:25Z |
| ROCm | clang-tools-extra           |   17610 | master                 | false | 2025-12-01T02:14:46Z |
| ROCm | rocFFT                      |    9449 | develop_deprecated     | false | 2025-10-22T00:10:25Z |
| ROCm | Thrust                      |    8176 | master                 | false | 2025-08-19T17:31:04Z |
| ROCm | ROCT-Thunk-Interface        |    7399 | master                 | false | 2025-11-25T20:22:00Z |
| ROCm | atmi                        |    5013 | master                 | true  | 2025-05-19T17:33:20Z |
| ROCm | ROCm.github.io              |    4378 | master                 | true  | 2025-11-16T19:45:12Z |
| ROCm | MIOpenGEMM                  |    4083 | master                 | true  | 2025-10-16T07:08:58Z |
| ROCm | ROCm-Device-Libs            |    2015 | deprecated             | true  | 2025-08-14T20:18:40Z |
| ROCm | clARMOR                     |    1907 | master                 | true  | 2025-12-22T07:11:46Z |
| ROCm | ROC-smi                     |     329 | master                 | false | 2025-12-23T21:01:40Z |
| ROCm | ROCm-docker                 |     258 | master                 | false | 2025-12-27T20:05:26Z |
| ROCm | ROCm-OpenCL-Driver          |     193 | master                 | false | 2024-05-10T11:11:41Z |
| ROCm | HCC-Example-Application     |      93 | master                 | true  | 2024-01-26T03:16:59Z |
| ROCm | LLVM-AMDGPU-Assembler-Extra |      76 | master                 | true  | 2025-11-11T14:10:32Z |
| ROCm | ROCm-ComputeABI-Doc         |      56 | master                 | true  | 2025-01-01T14:58:53Z |
| ROCm | StatusMonitor               |      32 | master                 | true  | 2025-07-02T05:36:53Z |
| ROCm | DirectGMA_CL                |      15 | master                 | true  | 2025-03-23T01:02:53Z |

#+NAME: rocmReposExclude
| schemastore          |
| transformers         |
| .github              |
| composablekernel     |
| hipBLAS              |
| hipBLAS-common       |
| hipBLASLt            |
| hipCUB               |
| hipDNN               |
| hipFFT               |
| hipRAND              |
| hipSOLVER            |
| hipSPARSE            |
| hipSPARSELt          |
| hipTensor            |
| MIOpen               |
| rocBLAS              |
| rocFFT               |
| rocPRIM              |
| rocRAND              |
| rocSOLVER            |
| rocSPARSE            |
| rocThrust            |
| rocWMMA              |
| amdsmi               |
| aqlprofile           |
| clr                  |
| hip                  |
| hipfile              |
| hipother             |
| hip-tests            |
| rccl                 |
| rdc                  |
| rocdbgapi            |
| rocdecode            |
| rocjpeg              |
| rocm-cor             |
| rocminfo             |
| rocmsmilib           |
| rocprofiler          |
| rocprofiler-compute  |
| rocprofiler-register |
| rocprofiler-sdk      |
| rocprofiler-systems  |
| rocr-debug-agent     |
| rocrruntime          |
| rocSHMEM             |
| roctracer            |

#+name: rocmRepos
#+begin_src emacs-lisp :var nrepos=100 :results replace vector value :exports code :noweb yes
(ghub-graphql
 (graphql-query ((organization
                  :arguments ((login . "ROCm"))
                  (repositories
                   :arguments ((first . 100)
                               (orderBy . ((field . UPDATED_AT)
                                           (direction . DESC))))
                   (edges
                    (node (owner login)
                          name
                          (defaultBranchRef prefix name)
                          url
                          updatedAt
                          isFork
                          isArchived)))))))
#+end_src

Filter the results, generate XML

#+name: rocmReposXML
#+begin_src emacs-lisp :var gqldata=rocmRepos repos-exclude=rocmReposExclude :results value html
(setq -gql-data gqldata)

;; no repos-core variable
;; (repos-core (flatten-list repos- core))

(let* ((repos-exclude (flatten-list repos-exclude)))
  (thread-first
    (thread-last
      (a-get* (nthcdr 0 gqldata) 'data 'organization 'repositories 'edges)
      (mapcar (lambda (el) (a-get* el 'node)))

      ;; filter archived repos
      (seq-filter (lambda (el) (not (a-get* el 'isFork))))
      (seq-filter (lambda (el) (not (a-get* el 'isArchived))))

      ;; filter repos in reposExclude list
      (seq-filter (lambda (el) (not (member (a-get* el 'name) repos-exclude))))
      (mapcar (lambda (el)
                (let* ((raw-name (a-get* el 'name))

                       ;; (repo-core? (member raw-name repos-core))

                       ;; (path-dirs (list "rocm" raw-name))
                       (path-dirs (list raw-name))

                       ;; (path-dirs (cond (repo-core? (list "core" raw-name))
                       ;;                 (t (list "misc" raw-name))))

                       (path (string-join path-dirs "/"))
                       (ref (concat (a-get* el 'defaultBranchRef 'prefix)
                                    (a-get* el 'defaultBranchRef 'name)))
                       (name (string-join (list (a-get* el 'owner 'login)
                                                (a-get* el 'name)) "/")))
                  (concat "<project"
                          " name=\"" name
                          "\" path=\"" path
                          "\" revision=\"" ref "\" remote=\"github\"/>")))))
    (cl-sort 'string-lessp :key 'downcase)
    (string-join "\n")))
#+end_src

#+RESULTS: rocmReposXML
#+begin_export html
<project name="ROCm/aiter" path="aiter" revision="refs/heads/main" remote="github"/>
<project name="ROCm/amd-anp" path="amd-anp" revision="refs/heads/main" remote="github"/>
<project name="ROCm/amd-rocm-programming-guide" path="amd-rocm-programming-guide" revision="refs/heads/main" remote="github"/>
<project name="ROCm/amd_matrix_instruction_calculator" path="amd_matrix_instruction_calculator" revision="refs/heads/main" remote="github"/>
<project name="ROCm/amdgpu" path="amdgpu" revision="refs/heads/master" remote="github"/>
<project name="ROCm/AMDMIGraphX" path="AMDMIGraphX" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/amdsmi" path="amdsmi" revision="refs/heads/amd-mainline" remote="github"/>
<project name="ROCm/aomp" path="aomp" revision="refs/heads/aomp-dev" remote="github"/>
<project name="ROCm/aotriton" path="aotriton" revision="refs/heads/main" remote="github"/>
<project name="ROCm/ATOM" path="ATOM" revision="refs/heads/main" remote="github"/>
<project name="ROCm/clr" path="clr" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/composable_kernel" path="composable_kernel" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/container-toolkit" path="container-toolkit" revision="refs/heads/main" remote="github"/>
<project name="ROCm/cupy" path="cupy" revision="refs/heads/master" remote="github"/>
<project name="ROCm/cvs" path="cvs" revision="refs/heads/main" remote="github"/>
<project name="ROCm/DeepEP" path="DeepEP" revision="refs/heads/main" remote="github"/>
<project name="ROCm/DeepSpeed" path="DeepSpeed" revision="refs/heads/master" remote="github"/>
<project name="ROCm/device-metrics-exporter" path="device-metrics-exporter" revision="refs/heads/main" remote="github"/>
<project name="ROCm/flash-attention" path="flash-attention" revision="refs/heads/tridao" remote="github"/>
<project name="ROCm/flashinfer" path="flashinfer" revision="refs/heads/amd-integration" remote="github"/>
<project name="ROCm/gpu-cluster-networking" path="gpu-cluster-networking" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/gpu-operator" path="gpu-operator" revision="refs/heads/main" remote="github"/>
<project name="ROCm/gpuaidev" path="gpuaidev" revision="refs/heads/main" remote="github"/>
<project name="ROCm/hcc" path="hcc" revision="refs/heads/clang_tot_upgrade" remote="github"/>
<project name="ROCm/hip" path="hip" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/hip-python" path="hip-python" revision="refs/heads/release/rocm-rel-7.1.0" remote="github"/>
<project name="ROCm/hip-tests" path="hip-tests" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/hipBLASLt" path="hipBLASLt" revision="refs/heads/develop_deprecated" remote="github"/>
<project name="ROCm/hipCUB" path="hipCUB" revision="refs/heads/develop_deprecated" remote="github"/>
<project name="ROCm/hipFFT" path="hipFFT" revision="refs/heads/develop_deprecated" remote="github"/>
<project name="ROCm/hipFile" path="hipFile" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/hipfort" path="hipfort" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/HIPIFY" path="HIPIFY" revision="refs/heads/amd-develop" remote="github"/>
<project name="ROCm/hipify_torch" path="hipify_torch" revision="refs/heads/master" remote="github"/>
<project name="ROCm/InferenceMAX" path="InferenceMAX" revision="refs/heads/main" remote="github"/>
<project name="ROCm/iris" path="iris" revision="refs/heads/main" remote="github"/>
<project name="ROCm/k8s-device-plugin" path="k8s-device-plugin" revision="refs/heads/master" remote="github"/>
<project name="ROCm/librocdxg" path="librocdxg" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/llama.cpp" path="llama.cpp" revision="refs/heads/amd-integration" remote="github"/>
<project name="ROCm/llvm-project" path="llvm-project" revision="refs/heads/amd-staging" remote="github"/>
<project name="ROCm/MAD" path="MAD" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/madengine" path="madengine" revision="refs/heads/main" remote="github"/>
<project name="ROCm/maxtext" path="maxtext" revision="refs/heads/main" remote="github"/>
<project name="ROCm/Megatron-LM" path="Megatron-LM" revision="refs/heads/rocm_dev" remote="github"/>
<project name="ROCm/MIOpen" path="MIOpen" revision="refs/heads/develop_deprecated" remote="github"/>
<project name="ROCm/MIVisionX" path="MIVisionX" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/mori" path="mori" revision="refs/heads/main" remote="github"/>
<project name="ROCm/numba-hip" path="numba-hip" revision="refs/heads/dev" remote="github"/>
<project name="ROCm/omnitrace" path="omnitrace" revision="refs/heads/amd-staging" remote="github"/>
<project name="ROCm/onnxruntime" path="onnxruntime" revision="refs/heads/main" remote="github"/>
<project name="ROCm/rccl" path="rccl" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/rccl-tests" path="rccl-tests" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/roc-optiq" path="roc-optiq" revision="refs/heads/main" remote="github"/>
<project name="ROCm/ROC-smi" path="ROC-smi" revision="refs/heads/master" remote="github"/>
<project name="ROCm/rocAL" path="rocAL" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/rocALUTION" path="rocALUTION" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/rocBLAS" path="rocBLAS" revision="refs/heads/develop_deprecated" remote="github"/>
<project name="ROCm/rocCV" path="rocCV" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/ROCdbgapi" path="ROCdbgapi" revision="refs/heads/amd-staging" remote="github"/>
<project name="ROCm/rocDecode" path="rocDecode" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/ROCgdb" path="ROCgdb" revision="refs/heads/amd-staging" remote="github"/>
<project name="ROCm/rocHPCG" path="rocHPCG" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/ROCm" path="ROCm" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/rocm-blogs" path="rocm-blogs" revision="refs/heads/release" remote="github"/>
<project name="ROCm/rocm-cmake" path="rocm-cmake" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/ROCm-docker" path="ROCm-docker" revision="refs/heads/master" remote="github"/>
<project name="ROCm/rocm-docs-core" path="rocm-docs-core" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/rocm-examples" path="rocm-examples" revision="refs/heads/amd-staging" remote="github"/>
<project name="ROCm/rocm-install-on-linux" path="rocm-install-on-linux" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/rocm-jax" path="rocm-jax" revision="refs/heads/master" remote="github"/>
<project name="ROCm/rocm-kpack" path="rocm-kpack" revision="refs/heads/main" remote="github"/>
<project name="ROCm/rocm-libraries" path="rocm-libraries" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/rocm-rag" path="rocm-rag" revision="refs/heads/main" remote="github"/>
<project name="ROCm/rocm-systems" path="rocm-systems" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/rocm_bandwidth_test" path="rocm_bandwidth_test" revision="refs/heads/amd-mainline" remote="github"/>
<project name="ROCm/rocMLIR" path="rocMLIR" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/rocmProfileData" path="rocmProfileData" revision="refs/heads/master" remote="github"/>
<project name="ROCm/ROCmValidationSuite" path="ROCmValidationSuite" revision="refs/heads/master" remote="github"/>
<project name="ROCm/rocPRIM" path="rocPRIM" revision="refs/heads/develop_deprecated" remote="github"/>
<project name="ROCm/rocprof-compute-viewer" path="rocprof-compute-viewer" revision="refs/heads/amd-mainline" remote="github"/>
<project name="ROCm/rocprof-trace-decoder" path="rocprof-trace-decoder" revision="refs/heads/amd-mainline" remote="github"/>
<project name="ROCm/rocprofiler-systems" path="rocprofiler-systems" revision="refs/heads/develop_deprecated" remote="github"/>
<project name="ROCm/rocPyDecode" path="rocPyDecode" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/rocr_debug_agent" path="rocr_debug_agent" revision="refs/heads/amd-staging" remote="github"/>
<project name="ROCm/rocSHMEM" path="rocSHMEM" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/rocSPARSE" path="rocSPARSE" revision="refs/heads/develop_deprecated" remote="github"/>
<project name="ROCm/rpp" path="rpp" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/SPIRV-LLVM-Translator" path="SPIRV-LLVM-Translator" revision="refs/heads/amd-develop" remote="github"/>
<project name="ROCm/system-acceptance-docs" path="system-acceptance-docs" revision="refs/heads/main" remote="github"/>
<project name="ROCm/Tensile" path="Tensile" revision="refs/heads/develop_deprecated" remote="github"/>
<project name="ROCm/tensorflow-upstream" path="tensorflow-upstream" revision="refs/heads/develop-upstream" remote="github"/>
<project name="ROCm/TheRock" path="TheRock" revision="refs/heads/main" remote="github"/>
<project name="ROCm/timemory" path="timemory" revision="refs/heads/timem" remote="github"/>
<project name="ROCm/torch_migraphx" path="torch_migraphx" revision="refs/heads/master" remote="github"/>
<project name="ROCm/TransferBench" path="TransferBench" revision="refs/heads/develop" remote="github"/>
<project name="ROCm/TransformerEngine" path="TransformerEngine" revision="refs/heads/dev" remote="github"/>
<project name="ROCm/triton" path="triton" revision="refs/heads/main_perf" remote="github"/>
<project name="ROCm/tritonBLAS" path="tritonBLAS" revision="refs/heads/main" remote="github"/>
<project name="ROCm/vllm" path="vllm" revision="refs/heads/main" remote="github"/>
#+end_export

Generate =rocm.xml=

#+begin_src xml :tangle rocm.xml :noweb yes
<manifest>
  <<rocmReposXML()>>
</manifest>
#+end_src
